name: Docker Image CD

on:
  repository_dispatch:
    types: [app_deployment]

env:
  REGISTRY: registry.digitalocean.com/simple-dimple-reg

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DO_TOKEN}}
        password: ${{ secrets.DO_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/simple-dimple:latest

    - name: Set up kubectl
      uses: matootie/dokube@v1.3.4
      with:
        personalAccessToken: ${{ secrets.DO_TOKEN }}
        clusterName: k8s-for-simple-dimple

    - name: New rollout
      run: kubectl rollout restart deployment/simple-dimple