name: VM monit

on:
  repository_dispatch:
    types: [vm_monit]
  
jobs:
  create-freebsd-install-kde:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "/dev/null"
          if_key_exists: fail 
      
      - name: DO login and doctl install
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      
      - name: Show uptime
        run: doctl compute ssh rtkach-fbsd --ssh-command "uptime"